
---
Only:
  environment: dev
---
SilverStripe\Core\Injector\Injector:
  Logger:
    class: Monolog\Logger
    constructor:
      0: App
      1:
        - '%$RavenHandler'
        - '%$StreamHandler'
        - '%$ChromePHPHandler'
        - '%$FirePHPHandler'
      2:
        - '%$MemoryPeakUsageProcessor'

  StreamHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      0: '../app_errors.log'
      1: 100

  Raven:
    class: Raven_Client
    constructor:
      0: https://8be6f939f6ba4f8595e40ab8927e0e1c:0ebe85050d7641df9911892fd807fa41@sentry.heyday.net.nz/107

---
Only:
  environment: test
---
SilverStripe\Core\Injector\Injector:
  Logger:
    class: Monolog\Logger
    constructor:
      0: App
      1:
        - '%$RavenHandler'
        - '%$StreamHandler'
        - '%$ChromePHPHandler'
        - '%$FirePHPHandler'
      2:
        - '%$MemoryPeakUsageProcessor'

  StreamHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      0: '../../app_errors.log'
      1: 100

  Raven:
    class: Raven_Client
    constructor:
      0: https://8be6f939f6ba4f8595e40ab8927e0e1c:0ebe85050d7641df9911892fd807fa41@sentry.heyday.net.nz/107

---
Only:
  environment: live
---
SilverStripe\Core\Injector\Injector:
  Logger:
    class: Monolog\Logger
    constructor:
      0: App
      1:
        - '%$RavenHandler'
        - '%$StreamHandler'
      2:
        - '%$MemoryPeakUsageProcessor'

  StreamHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      0: '../../app_errors.log'
      1: 400

  Raven:
    class: Raven_Client
    constructor:
      0: # Production Sentry key goes here. You should really set this.

---
Name: custom_logging
---
SilverStripe\Core\Injector\Injector:
  LoggerBridge:
    class: 'Camspiers\LoggerBridge\LoggerBridge'
    constructor:
      0: '%$Logger'
    properties:
      ReportBacktrace: true

  RavenHandler:
    class: Monolog\Handler\RavenHandler
    constructor:
      0: '%$Raven'

  ChromePHPHandler:
    class: Monolog\Handler\ChromePHPHandler

  FirePHPHandler:
    class: Monolog\Handler\FirePHPHandler

  MemoryPeakUsageProcessor:
    class: Monolog\Processor\MemoryPeakUsageProcessor